spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'

server:
  error:
    include-message: always
    include-binding-errors: always

login:
  app:
    jwtExpirationMs: '86400000'
    jwtCookieName: login
    jwtSecret: loginSecretKey